### ISSUE TITLE
 Can this pipeline compare 2 samples digested by different enzymes?

### ISSUE THREAD

**Issue by qianXX** [SmythLab/diffHic#4]
Hi！

I‘m working on detecting differential genomic interactions with two samples which were digested by different enzymes. When I use diffHiC pipeline, I got one error :

Error in curfuns[[lib]]() : 
  anchor1 index outside range of fragment object
Calls: squareCounts -> <Anonymous>

I guess this may be due to the different digestive enzymes used in my data.

**Comment by LTLA** [comment]
It's pretty much as you've concluded, the package doesn't know how to handle samples digested by different enzymes. I don't know whether it's a good idea to do such a comparison, but if you must, you can pretend that it's DNAse-Hi-C and follow the relevant instructions in the user's guide. This will ignore the restriction sites when setting up bins across the genome. I would guess that the bins need to be fairly large to average out any biases caused by differences in the restriction site profile.

If you only have two samples, there is another problem - of not having any replicates - that you'll need to deal with later.

**Comment by qianXX** [comment]
OK! Thanks for your reply.
