### ISSUE TITLE
[Question] Reason for clusterPair's strict dependence on ReverseStrictGInteractions?

### ISSUE THREAD

**Issue by srcoulombe** [SmythLab/diffHic#6]
Hi! 
I'm trying to run diffHic on inter-chromosomal matrices, and I've hit a wall I can't really explain. Everything runs well up until I try to use the ```diClusters``` function to cluster individual bin-pairs into differential interactions. I checked and ```diClusters``` calls ```clusterPairs``` which itself contains the line ```lapply(all.data, FUN = .check_StrictGI)```. 

This stops me from using ```diClusters```, since the interactions in my inter-chromosomal matrices don't satisfy the requirements for the ReverseStrictGInteractions class. But I don't understand why only ReverseStrictGInteractions are accepted in this function.

**Comment by srcoulombe** [comment]
Here is some code to show what I mean in case my explanation was confusing:
```
# Setting up the object.
a <- 10
b <- 20
regions <- GRanges(rep(c("chrA", "chrB"), c(a, b)), IRanges(c(1:a, 1:b), c(1:a, 1:b)))

set.seed(3423)
all.anchor1 <- sample(length(regions), 50, replace=TRUE)
all.anchor2 <- as.integer(runif(50, 1, all.anchor1+1))
y <- InteractionSet(matrix(0, 50, 1), 
    GInteractions(anchor1=all.anchor1, anchor2=all.anchor2, regions=regions, mode="reverse"),
    colData=DataFrame(lib.size=1000), metadata=List(width=1))

# Clustering; note, small tolerances are used in this toy example.
clusterPairs(y, tol=1) # works fine
clusterPairs(y, tol=3) # works fine

z <- InteractionSet(matrix(0, 50, 1), 
    GInteractions(anchor1=all.anchor1, anchor2=all.anchor2, regions=regions, mode="normal"), # not ReverseStrictGInteractions 
    colData=DataFrame(lib.size=1000), metadata=List(width=1))

clusterPairs(z, tol=1)
Error in FUN(X[[i]], ...) : 
  'interactions' slot of InteractionSet must be a 'ReverseStrictGInteractions'
```

**Comment by LTLA** [comment]
To be honest, I don't remember. But if I had to guess, it's probably because I was lazy. Way back in the day, I was using my custom `DIList` object (I think that was its name, can't remember exactly) and this object had the same constraints as a `ReverseStrictGInteractions`. In fact, the entire reason for the existence of `ReverseStrictGInteractions` was so that I could use it to directly replace the old `DIList` in **diffHic** without having to worry about handling the non-strict case.

In your case, it should be as simple as just coercing your `GInteractions` into a ` ReverseStrictGInteractions`; IIRC you should be able to do so with `as(gi, "ReverseStrictGInteractions)`. Or maybe `swapAnchors()`, I don't remember. I suspect I could very well have done this inside `clusterPairs` automatically, so that the user would never even notice... but I didn't. Don't remember why, probably couldn't be bothered when all the input objects coming through **diffHic** were already RSGIs anyway.

**Comment by srcoulombe** [comment]
Thanks for the quick reply man!
For anyone who runs into this issue in the future, here's the code snippet including Aaron's suggestion:

```
# Setting up the object.
a <- 10
b <- 20
regions <- GRanges(rep(c("chrA", "chrB"), c(a, b)), IRanges(c(1:a, 1:b), c(1:a, 1:b)))

set.seed(3423)
all.anchor1 <- sample(length(regions), 50, replace=TRUE)
all.anchor2 <- as.integer(runif(50, 1, all.anchor1+1))
y <- InteractionSet(matrix(0, 50, 1), 
    GInteractions(anchor1=all.anchor1, anchor2=all.anchor2, regions=regions, mode="reverse"),
    colData=DataFrame(lib.size=1000), metadata=List(width=1))

# Clustering; note, small tolerances are used in this toy example.
clusterPairs(y, tol=1) # works fine
clusterPairs(y, tol=3) # works fine

z <- InteractionSet(matrix(0, 50, 1), 
    GInteractions(anchor1=all.anchor1, anchor2=all.anchor2, regions=regions, mode="normal"), # not ReverseStrictGInteractions 
    colData=DataFrame(lib.size=1000), metadata=List(width=1))

clusterPairs(z, tol=1)
Error in FUN(X[[i]], ...) : 
  'interactions' slot of InteractionSet must be a 'ReverseStrictGInteractions'

interactions(z) <- as(interactions(z), "ReverseStrictGInteractions")
clusterPairs(z, tol=1) # now works
```
